<!DOCTYPE html>
<html lang="en">
	<head>
        <meta charset="UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Phalcon PHP Framework</title>
        <?php $this->assets->outputCss(); ?>
        <?php $this->assets->outputJs('header'); ?>
	</head>
	<body screen_capture_injected="true">
        <?php echo $this->getContent(); ?>
        <?php $this->assets->outputJs('footer'); ?>
	</body>
</html>